name: Podium WebChat Form

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Podium Chat Widget Tests
        uses: cypress-io/github-action@v4
        with:
          command: npm run test:ci
